language: generic
services:
  - docker

cache:
  directories:
    - $HOME/.ccache

git:
  quiet: true

env:
  global:
    - CCACHE_DIR=$HOME/.ccache
  matrix:
    - ROS_DISTRO="dashing" ROS_REPO=main
    - ROS_DISTRO="dashing" ROS_REPO=testing
    - ROS_DISTRO="foxy" ROS_REPO=main
    - ROS_DISTRO="foxy" ROS_REPO=testing

install:
  - git clone --quiet --depth=1 -b master https://github.com/ros-industrial/industrial_ci.git .industrial_ci

script:
  - .industrial_ci/travis.sh
